"""Validated data contracts shared by CLI, harness, and worker."""

from .actions import (
    Action,
    ActionCatalogEntry,
    MeshExtrudeRegion,
    MeshSmoothRegion,
    MeshSubdivide,
    MeshTransformRegion,
    NormalizedRegion,
    ObjectJoin,
    ObjectShadeSmooth,
    action_capability_summary,
    action_catalog,
    modeling_action_semantics,
    parse_action,
)
from .construction import (
    MAX_COMPLETION_CRITERIA,
    MIN_COMPLETION_CRITERIA,
    ConstructionItem,
    ConstructionPlan,
    WorkItemActionBatch,
    work_item_response_requirements,
)
from .critique import (
    VisualCritique,
    VisualIssue,
    VisualIssueDetail,
    VisualIssueDetailWire,
    VisualIssueDiscovery,
    VisualIssueDiscoveryWire,
    VisualIssueSummary,
)
from .execution import (
    ActionExecutionFailure,
    FailureKind,
    ProposalValidationErrorDetail,
    ProposalValidationFeedback,
    WorkItemExecutionOutcome,
)
from .inspection import (
    AtlasLayout,
    CameraCandidate,
    CandidateDiagnostic,
    CandidateSurvey,
    InspectionAtlasManifest,
    InspectionCameraPlan,
    InspectionReview,
    InspectionReviewWire,
)
from .target import FormTrait, TargetBrief, TargetBriefArtifact
from .viewport import (
    ViewportFraming,
    ViewportObservation,
    ViewportObservationRequest,
    ViewportOrientation,
    ViewportProjection,
    ViewportView,
)

__all__ = [
    "Action",
    "ActionExecutionFailure",
    "ActionCatalogEntry",
    "AtlasLayout",
    "CameraCandidate",
    "CandidateDiagnostic",
    "CandidateSurvey",
    "ConstructionItem",
    "ConstructionPlan",
    "FormTrait",
    "FailureKind",
    "InspectionAtlasManifest",
    "InspectionCameraPlan",
    "InspectionReview",
    "InspectionReviewWire",
    "MeshExtrudeRegion",
    "MeshSmoothRegion",
    "MeshSubdivide",
    "MeshTransformRegion",
    "MAX_COMPLETION_CRITERIA",
    "MIN_COMPLETION_CRITERIA",
    "NormalizedRegion",
    "ObjectJoin",
    "ObjectShadeSmooth",
    "ProposalValidationErrorDetail",
    "ProposalValidationFeedback",
    "TargetBrief",
    "TargetBriefArtifact",
    "VisualCritique",
    "VisualIssue",
    "VisualIssueDetail",
    "VisualIssueDetailWire",
    "VisualIssueDiscovery",
    "VisualIssueDiscoveryWire",
    "VisualIssueSummary",
    "WorkItemActionBatch",
    "WorkItemExecutionOutcome",
    "ViewportFraming",
    "ViewportObservation",
    "ViewportObservationRequest",
    "ViewportOrientation",
    "ViewportProjection",
    "ViewportView",
    "action_capability_summary",
    "action_catalog",
    "modeling_action_semantics",
    "parse_action",
    "work_item_response_requirements",
]
