"""Validated data contracts shared by CLI, harness, and worker."""

from .actions import (
    Action,
    ActionCatalogEntry,
    MeshExtrudeRegion,
    MeshSmoothRegion,
    MeshTransformRegion,
    NormalizedRegion,
    ObjectJoin,
    ObjectShadeSmooth,
    action_capability_summary,
    action_catalog,
    parse_action,
)
from .construction import ConstructionItem, ConstructionPlan, WorkItemActionBatch
from .critique import (
    VisualCritique,
    VisualIssue,
    VisualIssueDetail,
    VisualIssueDetailWire,
    VisualIssueDiscovery,
    VisualIssueDiscoveryWire,
    VisualIssueSummary,
)
from .execution import ActionExecutionFailure, FailureKind, WorkItemExecutionOutcome
from .inspection import (
    AtlasLayout,
    CameraCandidate,
    CandidateDiagnostic,
    CandidateSurvey,
    InspectionAtlasManifest,
    InspectionCameraPlan,
    InspectionReview,
    InspectionReviewWire,
)
from .target import FormTrait, TargetBrief, TargetBriefArtifact

__all__ = [
    "Action",
    "ActionExecutionFailure",
    "ActionCatalogEntry",
    "AtlasLayout",
    "CameraCandidate",
    "CandidateDiagnostic",
    "CandidateSurvey",
    "ConstructionItem",
    "ConstructionPlan",
    "FormTrait",
    "FailureKind",
    "InspectionAtlasManifest",
    "InspectionCameraPlan",
    "InspectionReview",
    "InspectionReviewWire",
    "MeshExtrudeRegion",
    "MeshSmoothRegion",
    "MeshTransformRegion",
    "NormalizedRegion",
    "ObjectJoin",
    "ObjectShadeSmooth",
    "TargetBrief",
    "TargetBriefArtifact",
    "VisualCritique",
    "VisualIssue",
    "VisualIssueDetail",
    "VisualIssueDetailWire",
    "VisualIssueDiscovery",
    "VisualIssueDiscoveryWire",
    "VisualIssueSummary",
    "WorkItemActionBatch",
    "WorkItemExecutionOutcome",
    "action_capability_summary",
    "action_catalog",
    "parse_action",
]
